Created [html,css] For Seller Page
CA-G12/Team7- pull request #9
Opened 2022-07-26 13:07 UTC by riyadsalem

Release #3 is Completed

2022-07-26 18:06 UTC, mohmmed23 requested changes

2022-07-26 18:06 UTC, dev-mohmmed-alshorafa commented on seller/seller.html
>            <img src="img/UntitledDesign.png" alt="logo Website" />
remove this

2022-07-26 18:06 UTC, mohmmed23 commented on seller/seller.html
>        <div id="navbar-content" class="navbar-content navbar-hidden">
change div to nav

2022-07-26 18:06 UTC, mohmmed23 commented on seller/seller.html
> +        <div class="add-product-content">
change div to form

2022-07-26 18:06 UTC, mohmmed23 commented on seller/seller.html
> +        <section id="product-list" class="wrap-product-list">
change section to figure

2022-07-26 18:06 UTC, mohmmed23 commented on seller/seller.html
> +              <div class="info-product">
change div to figcaption

2022-07-27 06:08 UTC, riyadsalem commented
#3 is Completed.

2022-07-27 06:13 UTC, mohmmed23 approved these changes

2022-07-27 06:24 UTC, bayan2002 approved these changes

2022-07-27 06:26 UTC, merged